ApiService/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApiService.Areas.Admin.Bl;
using ApiService.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace ApiService.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SliderController : Controller
    {
        IClsSlider ctx;
        public SliderController(IClsSlider service)
        {
            ctx = service;
        }
        public IActionResult SliderDT()
        {
            return View(ctx.GetSliders());
        }
        public IActionResult Edit(int? Id)
        {
            if (Id == null)
                return View();
            else
            {
                return View(ctx.GetById(Convert.ToInt32(Id)));
            }
        }

        public IActionResult Delete(int Id)
        {
            ctx.Delete(Id);
            return RedirectToAction("SliderDT");
        }

        [HttpPost]
        public async Task<IActionResult> Save(TbSlider slider, List<IFormFile> Files)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in Files)
                {
                    if (file.Length > 0)
                    {
                        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                        using (var stream = System.IO.File.Create(filePaths))
                        {
                            await file.CopyToAsync(stream);
                        }
                        slider.SliderImage = ImageName;
                    }
                }

                if (slider.SliderId == 0)
                    ctx.Add(slider);
                else
                    ctx.Edit(slider);
                return RedirectToAction("SliderDT");
            }
            else
                return RedirectToAction("Edit");
        }
    }
}

ApiService/Areas/Admin/Views/Slider/Edit.cshtml
@model TbSlider

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Slider Form</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form enctype="multipart/form-data"
                      method="post" role="form" asp-controller="Slider" asp-action="Save">
                    <div class="card-body">
                        <div class="form-group">
                            @if(Model != null)
                            {
                                <input type="hidden" asp-for="SliderId" />
                            }
                        </div>
                        <div class="form-group">
                            <label>Descreption</label>
                            <input asp-for="Descreption" type="text"
                                   class="form-control" placeholder="Enter Descreption">
                            <span class="col-form-label text-danger" asp-validation-for="Descreption"></span>
                        </div>
                        <div class="form-group">
                            <label>Long Descreption</label>
                            <input asp-for="LongDescreption" type="text"
                                   class="form-control" placeholder="Enter Long Descreption">
                            <span class="col-form-label text-danger" asp-validation-for="LongDescreption"></span>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">File input</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input asp-for="SliderImage" type="file" name="Files" class="custom-file-input">
                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">Upload</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <a class="btn btn-info mx-4" asp-action="SliderDT">Back</a>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>

    </div>
    <!-- /.row -->
</div><!-- /.container-fluid -->



@section Scripts
    {
    <script src="~/Admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
}
<!-- bs-custom-file-input -->

ApiService/Areas/Admin/Views/Slider/SliderDT.cshtml
@model List<TbSlider>
@section Styles
{
    <link href="~/css/dataTable.min.css" rel="stylesheet" />

}


<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">


                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Slider Data</h3>
                        <br />
                        <a asp-action="Edit" class="btn btn-info my-2">New Slider</a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Slider Id</th>
                                    <th>Slider Image</th>
                                    <th>Description</th>
                                    <th>Long Description</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var slider in Model)
                                {
                                    <tr>
                                        <td>@slider.SliderId</td>
                                        <td>
                                            <img src="@string.Format("/Uploads/{0}",slider.SliderImage)" width="130" height="50" />
                                        </td>
                                        <td>@slider.Descreption</td>
                                        <td>@slider.LongDescreption</td>
                                        <td> <a asp-action="Edit" asp-route-Id="@slider.SliderId" class="btn btn-info">Edit</a></td>
                                        <td> <a asp-action="Delete" asp-route-Id="@slider.SliderId" class="btn btn-danger">Delete</a></td>
                                    </tr>
                                }


                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Slider Id</th>
                                    <th>Slider Image</th>
                                    <th>Description</th>
                                    <th>Long Description</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->





@section Scripts
{

    <script src="~/js/dataTable.min.js"></script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}