ApiService/Areas/Admin/Controllers/ItemImageController.cs
using ApiService.Areas.Admin.Bl;
using ApiService.Areas.Admin.Models;
using ApiService.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ApiService.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ItemImageController : Controller
    {
        IClsItemImage ctx;
        IClsItem ctx2;
        public ItemImageController(IClsItemImage service , IClsItem service2)
        {
            ctx = service;
            ctx2 = service2;
        }
        public IActionResult ItemImageDT()
        {
            List<ItemImageModel> lstItemImages = ctx.GetAllImages();
            return View(lstItemImages);
        }
        public IActionResult Edit(int? Id)
        {
            ViewBag.ItemsNames = ctx2.GetAllItems();

            if (Id == null)
                return View();
            else
            {
                return View(ctx.GetById(Convert.ToInt32(Id)));
            }
        }
        public IActionResult Delete(int Id)
        {
            ctx.Delete(Id);
            return RedirectToAction("ItemImageDT");
        }

        [HttpPost]
        public async Task<IActionResult> Save(TbImage image, List<IFormFile> Files)
        {
            if (ModelState.IsValid)
            {
                foreach (var file in Files)
                {
                    if (file.Length > 0)
                    {
                        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                        using (var stream = System.IO.File.Create(filePaths))
                        {
                            await file.CopyToAsync(stream);
                        }
                        image.ImageName = ImageName;
                    }
                }

                if (image.ImageId == 0)
                    ctx.Add(image);
                else
                    ctx.Edit(image);
                return RedirectToAction("ItemImageDT");
            }
            else
                return RedirectToAction("Edit");
        }
    }
}

ApiService/Areas/Admin/Views/ItemImage/Edit.cshtml
@model TbImage

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Image Form</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form enctype="multipart/form-data"
                      method="post" role="form" asp-controller="ItemImage" asp-action="Save">
                    <div class="card-body">
                        <div class="form-group">
                           @if(Model != null)
                            {
                                <input type="hidden" asp-for="ImageId" />
                            }
                        </div>
                        <div class="form-group">
                            <label>Image Name</label>
                            <select class="form-control" asp-for="ItemId"
                                    asp-items="@(new SelectList(ViewBag.ItemsNames,"ItemId","ItemName"))">
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">File input</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input asp-for="ImageName" type="file" name="Files" class="custom-file-input">
                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">Upload</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <a class="btn btn-info mx-4" asp-action="ItemImageDT">Back</a>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>

    </div>
    <!-- /.row -->
</div><!-- /.container-fluid -->



@section Scripts
    {
    <script src="~/Admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
}
<!-- bs-custom-file-input -->

ApiService/Areas/Admin/Views/ItemImage/ItemImageDT.cshtml
@model List<ItemImageModel>
@section Styles
{
    <link href="~/css/dataTable.min.css" rel="stylesheet" />
}


<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">


                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Item Image Data</h3>
                        <br />
                        <a asp-action="Edit" class="btn btn-info my-2">New Item Image</a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>ItemId</th>
                                    <th>ItemName</th>
                                    <th>ImageId</th>
                                    <th>Image</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var itemImage in Model)
                                {
                                    <tr>
                                        <td>@itemImage.ItemId</td>
                                        <td>@itemImage.ItemName</td>
                                        <td>@itemImage.ImageId</td>
                                        <td>
                                            <img src="@string.Format("/Uploads/{0}",itemImage.ImageName)" style="width:100%" height="50" />
                                        </td>
                                        <td><a asp-action="Edit" asp-route-Id="@itemImage.ImageId" class="btn btn-info">Edit</a></td>
                                        <td><a asp-action="Delete" asp-route-Id="@itemImage.ImageId" class="btn btn-danger">Delete</a></td>

                                    </tr>
                                }


                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ItemId</th>
                                    <th>ItemName</th>
                                    <th>ImageId</th>
                                    <th>Image</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->





@section Scripts
{

    <script src="~/js/dataTable.min.js"></script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}