ApiService/Areas/Admin/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApiService.Models;
using ApiService.Areas.Admin.Bl;

using System.Dynamic;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace ApiService.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ItemController : Controller
    {
        IClsItem ctx;
        public ItemController(IClsItem service)
        {
            ctx = service;
        }
        public IActionResult ItemDT()
        {
            List<ItemModel> lstModel = ctx.GetAllItems();
            return View(lstModel);
        }

        public IActionResult Edit(int? Id)
        {
            ViewBag.Categories = ctx.GetSubCategories();

            //ViewData["ItemsCount"] = ctx.GetSubCategories();

            if (Id == null)
                return View();
            else
            {
                return View(ctx.GetItem(Convert.ToInt32(Id)));
            }
        }

        public IActionResult Delete(int Id)
        {
            ctx.Delete(Id);
            return RedirectToAction("ItemDT");    
        }

        [HttpPost]
        public async Task<IActionResult> Save(TbItem item , List<IFormFile> Files)
        {
            if(item.Quantity <= 0)
                return RedirectToAction("Edit");

            if (ModelState.IsValid)
            {
                foreach (var file in Files)
                {
                    if (file.Length > 0)
                    {
                        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                        using (var stream = System.IO.File.Create(filePaths))
                        {
                            await file.CopyToAsync(stream);
                        }
                        item.ImageName = ImageName;
                    }
                }

                if (item.ItemId == 0)
                    ctx.Add(item);
                else
                    ctx.Edit(item);
                return RedirectToAction("ItemDT");
            }
            else
                return RedirectToAction("Edit");
        }
    }
}

ApiService/Areas/Admin/Views/Item/Edit.cshtml
@model TbItem

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Item Form</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form enctype="multipart/form-data"
                      method="post" role="form" asp-controller="Item" asp-action="Save">
                    <div class="card-body">
                        <div class="form-group">
                            @if (Model != null)
                            {
                                <input type="hidden" asp-for="ItemId" />
                            }
                        </div>
                        <div class="form-group">
                            <label>Item Name</label>
                            <input asp-for="ItemName"
                                   type="text" class="form-control" placeholder="Enter Item Name">
                            <span class="col-form-label text-danger" asp-validation-for="ItemName"></span>
                        </div>
                         <div class="form-group">
                            <label>Item Name Arabic</label>
                            <input asp-for="ItemNameAr"
                                   type="text" class="form-control" placeholder="Enter Item Name Arabic">
                            <span class="col-form-label text-danger" asp-validation-for="ItemNameAr"></span>
                        </div>
                        <div class="form-group">
                            <label>Sales Price</label>
                            <input asp-for="SalesPrice"
                                   type="number" class="form-control" placeholder="Enter Sales Price">
                            <span class="col-form-label text-danger" asp-validation-for="SalesPrice"></span>
                        </div>
                        <div class="form-group">
                            <label>Purchase Price</label>
                            <input asp-for="PurchasePrice" type="number"
                                   class="form-control" placeholder="Enter Purchase Price">
                            <span class="col-form-label text-danger" asp-validation-for="PurchasePrice"></span>
                        </div>
                        <div class="form-group">
                            <label>Category Name</label>
                            <select class="form-control" asp-for="SubCategoryId"
                                    asp-items="@(new SelectList(ViewBag.Categories,"SubCategoryId","SubCategoryName"))">
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Quantity</label>
                            <input asp-for="Quantity"
                                   type="number" class="form-control" placeholder="Enter Sales Price">
                            <span class="col-form-label text-danger" asp-validation-for="Quantity"></span>
                        </div>

                        <div class="form-group">
                            @*<label>Category Name</label>*@
                            <input type="hidden" value="1" asp-for="CategoryId">
                        </div>

                        @*<div class="form-group">
            <<label>SubCategory Name</label>
            <select class="form-control" asp-for="SubCategoryId" disabled
                    asp-items="@(new SelectList(ViewBag.Categories,"SubCategoryId","SubCategoryName"))">
            </select>
        </div>*@


                        <div class="form-group">
                            <label for="exampleInputFile">File input</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input asp-for="ImageName" type="file" name="Files" class="custom-file-input">
                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text">Upload</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <a class="btn btn-info mx-4" asp-action="ItemDT">Back</a>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>

    </div>
    <!-- /.row -->
</div><!-- /.container-fluid -->



@section Scripts
    {
    <script src="~/Admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
}
<!-- bs-custom-file-input -->

ApiService/Areas/Admin/Views/Item/ItemDT.cshtml
@model List<ItemModel>
@section Styles
{

    <link href="~/css/dataTable.min.css" rel="stylesheet" />
}


<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">


                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Items Data</h3>
                        <br />
                        <a asp-action="Edit" class="btn btn-info my-2">New Item</a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>ItemId</th>
                                    <th>ItemName</th>
                                    <th>ItemNameAr</th>
                                    <th>SalesPrice</th>
                                    <th>SubCategoryName</th>
                                    <th>Image</th>
                                    <th>Quantity</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.ItemId</td>
                                        <td>@item.ItemName</td>
                                        <td>@item.ItemNameAr</td>
                                        <td>@item.SalesPrice</td>
                                        <td>@item.SubCategoryName</td>
                                        <td>
                                            <img src="@string.Format("/Uploads/{0}",item.ImageName)" style="width:100%" height="50" />
                                        </td>
                                        <td>@item.Quantity</td>
                                        <td> <a asp-action="Edit" asp-route-Id="@item.ItemId" class="btn btn-info">Edit</a></td>
                                        <td> <a  asp-action="Delete" asp-route-Id="@item.ItemId" class="btn btn-danger">Delete</a></td>
                                    </tr>
                                }


                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ItemId</th>
                                    <th>ItemName</th>
                                    <th>ItemNameAr</th>
                                    <th>SalesPrice</th>
                                    <th>SubCategoryName</th>
                                    <th>Image</th>
                                    <th>Quantity</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->





@section Scripts
{


    <script src="~/js/dataTable.min.js"></script>
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}